(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"BSM Beam Dump",
  Authors -> {"S. Alipour-fard"},
  Emails -> {"samuelaf@mit.edu"},
  Institutions -> {"Massachusetts Institute of Technology"},
  Version -> "1.0"};

FR$ClassesTranslation={A -> V[1], e -> F[1], mu -> F[2], Ns -> S[1], Nf -> F[3], S -> S[2], phi -> S[3], V -> V[2], U -> V[3]};

FR$InteractionOrderPerturbativeExpansion={{BSM, 0}, {QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mel,
    Indices -> {},
    PropagatorLabel -> "e" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mmu,
    Indices -> {},
    PropagatorLabel -> "mu" },

S[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> Mns,
    Indices -> {},
    PropagatorLabel -> "Ns" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnf,
    Indices -> {},
    PropagatorLabel -> "Nf" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mS,
    Indices -> {},
    PropagatorLabel -> "S" },

S[3] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mphi,
    Indices -> {},
    PropagatorLabel -> "phi" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mV,
    Indices -> {},
    PropagatorLabel -> "V" },

V[3] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mU,
    Indices -> {},
    PropagatorLabel -> "U" }
}


(*        Definitions       *)

GaugeXi[ S[1] ] = GaugeXi[S[9]];
GaugeXi[ F[3] ] = GaugeXi[F[9]];
GaugeXi[ S[2] ] = GaugeXi[S[11]];
GaugeXi[ S[3] ] = GaugeXi[S[12]];
GaugeXi[ V[2] ] = GaugeXi[V[11]];
GaugeXi[ V[3] ] = GaugeXi[V[12]];

mel[ ___ ] := mel;
mmu[ ___ ] := mmu;
Mns[ ___ ] := Mns;
Mnf[ ___ ] := Mnf;
mS[ ___ ] := mS;
mphi[ ___ ] := mphi;
mV[ ___ ] := mV;
mU[ ___ ] := mU;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , -S[1] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[1] , -S[1] , V[1] ] == {{(-I)*gc2, 0}, {I*gc2, 0}},

C[ -F[1] , F[1] , S[2] ] == {{I*gc3, 0}, {I*gc3, 0}},

C[ -F[2] , F[2] , S[2] ] == {{I*gc4, 0}, {I*gc4, 0}},

C[ -F[1] , F[1] , S[3] ] == {{I*gc5L, 0}, {I*gc5R, 0}},

C[ -F[2] , F[2] , S[3] ] == {{I*gc6L, 0}, {I*gc6R, 0}},

C[ -F[1] , F[1] , V[1] ] == {{I*gc7, 0}, {I*gc7, 0}},

C[ -F[2] , F[2] , V[1] ] == {{I*gc8, 0}, {I*gc8, 0}},

C[ -F[3] , F[3] , V[1] ] == {{I*gc9, 0}, {I*gc9, 0}},

C[ -F[1] , F[1] , V[2] ] == {{gc10, 0}, {gc10, 0}},

C[ -F[2] , F[2] , V[2] ] == {{gc11, 0}, {gc11, 0}},

C[ -F[1] , F[1] , V[3] ] == {{gc12L, 0}, {gc12R, 0}},

C[ -F[2] , F[2] , V[3] ] == {{gc13L, 0}, {gc13R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc2 -> -EL,
     gc3 -> ySe,
     gc4 -> ySmu,
     gc5L -> -yphie,
     gc5R -> yphie,
     gc6L -> -yphimu,
     gc6R -> yphimu,
     gc7 -> -EL,
     gc8 -> -EL,
     gc9 -> EL,
     gc10 -> gVel,
     gc11 -> gVmu,
     gc12L -> -gUel,
     gc12R -> gUel,
     gc13L -> -gUmu,
     gc13R -> gUmu};

