ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=0D0)

      DOUBLE PRECISION MDL_MNF,MDL_MNS,MDL_MS,MDL_MU,MDL_MV,MDL_MEL
     $ ,MDL_MMU,MDL_MPHI

      COMMON/MASSES/ MDL_MNF,MDL_MNS,MDL_MS,MDL_MU,MDL_MV,MDL_MEL
     $ ,MDL_MMU,MDL_MPHI


      DOUBLE COMPLEX GC_1, GC_11

      COMMON/COUPLINGS/ GC_1, GC_11

