ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_alphaEM = ', MDL_ALPHAEM
      WRITE(*,*) 'mdl_ySe = ', MDL_YSE
      WRITE(*,*) 'mdl_ySmu = ', MDL_YSMU
      WRITE(*,*) 'mdl_yphie = ', MDL_YPHIE
      WRITE(*,*) 'mdl_yphimu = ', MDL_YPHIMU
      WRITE(*,*) 'mdl_gPrimakoff = ', MDL_GPRIMAKOFF
      WRITE(*,*) 'mdl_gVel = ', MDL_GVEL
      WRITE(*,*) 'mdl_gVmu = ', MDL_GVMU
      WRITE(*,*) 'mdl_gUel = ', MDL_GUEL
      WRITE(*,*) 'mdl_gUmu = ', MDL_GUMU
      WRITE(*,*) 'mdl_mel = ', MDL_MEL
      WRITE(*,*) 'mdl_mmu = ', MDL_MMU
      WRITE(*,*) 'mdl_Mns = ', MDL_MNS
      WRITE(*,*) 'mdl_Mnf = ', MDL_MNF
      WRITE(*,*) 'mdl_mS = ', MDL_MS
      WRITE(*,*) 'mdl_mphi = ', MDL_MPHI
      WRITE(*,*) 'mdl_mV = ', MDL_MV
      WRITE(*,*) 'mdl_mU = ', MDL_MU
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__alphaEM = ', MDL_SQRT__ALPHAEM
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'G = ', G
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '

