ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION MDL_SQRT__ALPHAEM,MDL_EE,MDL_EE__EXP__2,AS
     $ ,MDL_ALPHAEM,MDL_YSE,MDL_YSMU,MDL_YPHIE,MDL_YPHIMU
     $ ,MDL_GPRIMAKOFF,MDL_GVEL,MDL_GVMU,MDL_GUEL,MDL_GUMU

      COMMON/PARAMS_R/ MDL_SQRT__ALPHAEM,MDL_EE,MDL_EE__EXP__2,AS
     $ ,MDL_ALPHAEM,MDL_YSE,MDL_YSMU,MDL_YPHIE,MDL_YPHIMU
     $ ,MDL_GPRIMAKOFF,MDL_GVEL,MDL_GVMU,MDL_GUEL,MDL_GUMU


      DOUBLE COMPLEX MDL_COMPLEXI

      COMMON/PARAMS_C/ MDL_COMPLEXI


